# Generated by Django 2.2.6 on 2019-10-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('east_sensor_latitude', models.FloatField(default=-6.1825182)),
                ('east_sensor_longitude', models.FloatField(default=35.7413041)),
                ('west_sensor_latitude', models.FloatField(default=-6.1825182)),
                ('west_sensor_longitude', models.FloatField(default=35.7413041)),
                ('zipcode', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('road_intersect_name', models.CharField(max_length=50)),
            ],
        ),
    ]
