# Generated by Django 2.2.6 on 2019-10-15 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191015_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_detail',
            name='station_of_origin',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
