# Generated by Django 2.2.6 on 2019-10-16 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_train_detail_station_of_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='Gate_name',
        ),
        migrations.DeleteModel(
            name='gate',
        ),
    ]
