# Generated by Django 2.2.6 on 2019-10-16 07:23

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191016_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='gate_location',
            field=djgeojson.fields.PointField(default=6.2),
            preserve_default=False,
        ),
    ]
