# Generated by Django 2.2.6 on 2020-01-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_location_gate_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='gate_location',
        ),
    ]
