# Generated by Django 2.2.6 on 2020-01-29 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_location_gate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_detail',
            name='station_of_destination',
            field=models.CharField(default='hazina', max_length=50),
            preserve_default=False,
        ),
    ]
