# Generated by Django 2.2.6 on 2020-01-29 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_train_detail_station_of_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='gate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.location'),
        ),
    ]
