# Generated by Django 2.2.6 on 2020-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20200129_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_detail',
            name='train_home_station',
            field=models.CharField(default='', max_length=50),
        ),
    ]
