# Generated by Django 2.2.6 on 2020-01-29 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_train_detail_train_home_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='gate_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gate_name', models.CharField(max_length=50)),
                ('centre_latitude', models.FloatField()),
                ('centre_longitude', models.FloatField()),
                ('east_sensor_latitude', models.FloatField(default=-6.1825182)),
                ('east_sensor_longitude', models.FloatField(default=35.7413041)),
                ('west_sensor_latitude', models.FloatField(default=-6.1825182)),
                ('west_sensor_longitude', models.FloatField(default=35.7413041)),
                ('zipcode', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('road_intersect_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='gate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.gate_detail'),
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
