# Generated by Django 2.2.6 on 2020-01-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200129_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='train_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.train_detail'),
        ),
    ]
