# Generated by Django 2.2.6 on 2020-01-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200130_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='gate_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sensor_data',
            name='train_id',
            field=models.IntegerField(),
        ),
    ]
