# Generated by Django 2.2.6 on 2020-02-01 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200130_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_available_card',
            fields=[
                ('uuid_number', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bus_station',
            fields=[
                ('station_id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=220)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='entry_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_number', models.IntegerField(max_length=50)),
                ('entry_date_time', models.DateTimeField(auto_now_add=True)),
                ('bus_station', models.CharField(max_length=50)),
                ('entry_amount_deducted', models.FloatField(default=0, max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='exit_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_number', models.IntegerField(max_length=50)),
                ('exit_date_time', models.DateTimeField(auto_now_add=True)),
                ('bus_station', models.CharField(max_length=50)),
                ('exit_amount_deducted', models.FloatField(default=0, max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='machine_on_bus_stations',
            fields=[
                ('machine_id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=6)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='recharge_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_number', models.IntegerField(max_length=50)),
                ('initial_amount', models.FloatField(default=0, max_length=220)),
                ('recharged_amount', models.FloatField(default=0, max_length=220)),
                ('total_amount_recharged', models.FloatField(default=0, max_length=220)),
                ('place_of_recharge', models.FloatField(default=0, max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('national_id', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('type_of_registration', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=50)),
                ('current_amount', models.FloatField(default=0, max_length=220)),
                ('credit_amount', models.FloatField(default=0, max_length=220)),
                ('uuid_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.all_available_card')),
            ],
        ),
        migrations.RemoveField(
            model_name='admin_user',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='gate_detail',
        ),
        migrations.DeleteModel(
            name='sensor_data',
        ),
        migrations.DeleteModel(
            name='train_detail',
        ),
        migrations.DeleteModel(
            name='admin_user',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='question',
        ),
        migrations.AddField(
            model_name='bus_station',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.machine_on_bus_stations'),
        ),
    ]
