# Generated by Django 2.2.6 on 2020-02-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200201_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='exit_logs',
            new_name='entry_log',
        ),
        migrations.RenameModel(
            old_name='entry_logs',
            new_name='exit_log',
        ),
        migrations.RenameModel(
            old_name='machine_on_bus_stations',
            new_name='machine_on_bus_station',
        ),
        migrations.RenameModel(
            old_name='recharge_logs',
            new_name='recharge_log',
        ),
        migrations.RenameField(
            model_name='entry_log',
            old_name='exit_amount_deducted',
            new_name='entry_amount_deducted',
        ),
        migrations.RenameField(
            model_name='entry_log',
            old_name='exit_date_time',
            new_name='entry_date_time',
        ),
        migrations.RenameField(
            model_name='exit_log',
            old_name='entry_amount_deducted',
            new_name='exit_amount_deducted',
        ),
        migrations.RenameField(
            model_name='exit_log',
            old_name='entry_date_time',
            new_name='exit_date_time',
        ),
    ]
