# Generated by Django 2.2.6 on 2020-02-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_vendor_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='fare_collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_number', models.FloatField()),
                ('credit_revenue', models.FloatField()),
                ('debit_revenue', models.FloatField()),
                ('machine_id', models.FloatField()),
            ],
        ),
    ]
