# Generated by Django 2.2.6 on 2020-02-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_fare_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_on_bus_station',
            name='amount_deducting',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='all_available_card',
            name='uuid_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machine_on_bus_station',
            name='machine_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
