# Generated by Django 2.2.6 on 2020-02-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20200208_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_number', models.IntegerField()),
                ('recharged_amount', models.FloatField(default=0, max_length=220)),
                ('place_of_recharge', models.FloatField(default=0, max_length=220)),
                ('date_of_recharge', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='control_number',
        ),
    ]
