# Generated by Django 2.2.6 on 2020-02-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20200217_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='credit_amount',
            field=models.FloatField(default=0, max_length=220),
        ),
    ]
